library(shinytest2)


test_that("{shinytest2} recording: test_read_time_series_file", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_read_time_series_file",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_read_other_data_file", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_read_other_data_file",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "2")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "mympg.rds")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_scatter_plot_time_series", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_scatter_plot_time_series",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(plot_type = "2")
  Sys.sleep(0.5)
  app$set_inputs(x_scat = "Disp03")
  Sys.sleep(0.5)
  app$set_inputs(y_scat = "Temp007")
  Sys.sleep(0.5)
  app$set_inputs(color = "Year")
  Sys.sleep(0.5)
  app$click("refresh6")
  Sys.sleep(0.5)
  app$set_inputs(back_colour_scatter_plot = TRUE)
  Sys.sleep(0.5)
  app$click("refresh6")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_scatter_plot_4d_time_series", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_scatter_plot_4d_time_series",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(plot_type = "3")
  Sys.sleep(0.5)
  app$set_inputs(z_scat4d = "Temp007")
  Sys.sleep(0.5)
  app$set_inputs(color4d = "Rainfall")
  Sys.sleep(0.5)
  app$click("refresh3")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_time_series_plot", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_time_series_plot",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(plot_type = "1")
  Sys.sleep(0.5)
  app$set_inputs(vars_left_open = TRUE, allow_no_input_binding_ = TRUE)
  Sys.sleep(0.5)
  app$set_inputs(vars_left = "Disp01")
  Sys.sleep(0.5)
  app$set_inputs(vars_left = c("Disp01", "Disp02"))
  Sys.sleep(0.5)
  app$set_inputs(vars_left_open = FALSE, allow_no_input_binding_ = TRUE)
  Sys.sleep(0.5)
  app$set_inputs(vars_right_open = TRUE, allow_no_input_binding_ = TRUE)
  Sys.sleep(0.5)
  app$set_inputs(vars_right = "Temp007")
  Sys.sleep(0.5)
  app$set_inputs(vars_right = c("Temp007", "Temp014"))
  Sys.sleep(0.5)
  app$set_inputs(vars_right_open = FALSE, allow_no_input_binding_ = TRUE)
  Sys.sleep(0.5)
  app$click("refresh5")
  Sys.sleep(0.5)
  app$set_inputs(colours2 = TRUE)
  Sys.sleep(0.5)
  app$click("refresh5")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_scatter_plot_other_data", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_scatter_plot_other_data",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "2")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "mympg.rds")
  Sys.sleep(0.5)
  app$set_inputs(plot_type = "2")
  Sys.sleep(0.5)
  app$set_inputs(y_scat = "horsep")
  Sys.sleep(0.5)
  app$set_inputs(color = "cyl")
  Sys.sleep(0.5)
  app$click("refresh6")
  Sys.sleep(0.5)
  app$set_inputs(back_colour_scatter_plot = TRUE)
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_scatter_plot_4d_other_data", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_scatter_plot_4d_other_data",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "2")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "mympg.rds")
  Sys.sleep(0.5)
  app$set_inputs(plot_type = "3")
  Sys.sleep(0.5)
  app$set_inputs(y_scat4d = "horsep")
  Sys.sleep(0.5)
  app$set_inputs(z_scat4d = "weight")
  Sys.sleep(0.5)
  app$set_inputs(color4d = "cyl")
  Sys.sleep(0.5)
  app$click("refresh3")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_predict_time_series", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_predict_time_series",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(inputs = "Tem group")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev"))
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev", "Year"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_predict_other_data", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_predict_other_data",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "2")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "mympg.rds")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(target = "mpg")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("accel", "cyl", "disp", "horsep", "modyear", "origin", "weight"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_pdps_time_series", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_pdps_time_series",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(inputs = "Tem group")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev"))
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev", "Year"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "interpretation")
  Sys.sleep(0.5)
  app$set_inputs(x_dp2 = "Lev")
  Sys.sleep(0.5)
  app$set_inputs(x_dp3 = "Year")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_pdps_other_data", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_pdps_other_data",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "2")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "mympg.rds")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(target = "mpg")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("accel", "cyl", "disp", "horsep", "modyear", "origin", "weight"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "interpretation")
  Sys.sleep(0.5)
  app$set_inputs(x_dp2 = "modyear")
  Sys.sleep(0.5)
  app$set_inputs(x_dp3 = "cyl")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_convex_hull", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_convex_hull",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(inputs = "Tem group")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev"))
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev", "Year"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "exploration")
  Sys.sleep(0.5)
  app$set_inputs(plot_type = "2")
  Sys.sleep(0.5)
  app$set_inputs(color = "Temp007")
  Sys.sleep(0.5)
  app$click("refresh6")
  Sys.sleep(0.5)
  app$set_inputs(only_train_hull = TRUE)
  Sys.sleep(0.5)
  app$click("refresh6")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_train_test_range_time_series", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_train_test_range_time_series",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "1")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "DummyData.xlsx")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(inputs = "Tem group")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev"))
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("Tem group", "Lev", "Year"))
  Sys.sleep(0.5)
  app$set_inputs(train_years = c("2000-01-02", "2011-10-15"))
  Sys.sleep(0.5)
  app$set_inputs(test_years = c("2011-10-16", "2015-12-27"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_inputs(train_test = "2")
  Sys.sleep(0.5)
  app$set_inputs(train_perc = 50)
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_inputs(train_perc = 20)
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})


test_that("{shinytest2} recording: test_train_test_range_other_data", {
  app <- AppDriver$new(variant = platform_variant(), name = "test_train_test_range_other_data",
      height = 943, width = 1577)
  Sys.sleep(0.5)
  app$set_inputs(data_type = "2")
  Sys.sleep(0.5)
  app$upload_file(file_new_data = "mympg.rds")
  Sys.sleep(0.5)
  app$set_inputs(tabs = "fit")
  Sys.sleep(0.5)
  app$set_inputs(target = "mpg")
  Sys.sleep(0.5)
  app$set_inputs(inputs = c("accel", "cyl", "disp", "horsep", "modyear", "origin", "weight"))
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_inputs(test_perc_2 = 45)
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_inputs(random_data = FALSE)
  Sys.sleep(0.5)
  app$click("build")
  Sys.sleep(0.5)
  app$click("refresh_pred_data")
  Sys.sleep(0.5)
  app$set_window_size(height = 943, width = 1577)
  Sys.sleep(2)
  app$expect_screenshot(threshold = 25)
})
